# Generated by Django 5.0.1 on 2024-01-21 02:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='beneficiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_no', models.CharField(blank=True, max_length=512, null=True)),
                ('first_name', models.CharField(default='', max_length=64)),
                ('second_name', models.CharField(default='', max_length=64)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('nationality', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=5, null=True)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('national_id', models.CharField(max_length=20)),
                ('national_id_exp_date', models.DateField(null=True)),
                ('is_qualified', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=128)),
                ('marital_status', models.CharField(max_length=64)),
                ('educational_level', models.CharField(max_length=128, null=True)),
                ('health_status', models.CharField(max_length=64, null=True)),
                ('disease_type', models.CharField(max_length=128, null=True)),
                ('work_status', models.CharField(max_length=64, null=True)),
                ('employer', models.CharField(max_length=128, null=True)),
                ('death_date_father_husband', models.DateField(null=True)),
                ('washing_place', models.CharField(max_length=64, null=True)),
                ('is_benefiting', models.BooleanField(default=False)),
                ('receivedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('reviewedAt', models.DateTimeField(null=True)),
                ('bank_type', models.CharField(max_length=64, null=True)),
                ('bank_iban', models.CharField(max_length=32, null=True)),
                ('family_issues', models.JSONField(default=list)),
                ('family_needs', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('account', models.CharField(max_length=55, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=55)),
            ],
        ),
        migrations.CreateModel(
            name='individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('account', models.CharField(max_length=55, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=55)),
            ],
        ),
        migrations.CreateModel(
            name='Individual_supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('second_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=5, null=True)),
                ('national_id', models.CharField(max_length=20)),
                ('national_id_exp_date', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=64)),
                ('marital_status', models.CharField(max_length=64)),
                ('educational_level', models.CharField(max_length=128, null=True)),
                ('work_status', models.CharField(max_length=64, null=True)),
                ('employer', models.CharField(max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('orphan_number', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='supporter_operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=55)),
                ('category', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=5, null=True)),
                ('phonenumber', models.CharField(max_length=15, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiary_attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=256, null=True)),
                ('file_object', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_file_directory)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='beneficiary_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.CharField(max_length=64)),
                ('street_name', models.CharField(max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=64)),
                ('additional_number', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=64)),
                ('location_url', models.CharField(max_length=1064)),
                ('housing_type', models.CharField(max_length=64)),
                ('housing_ownership', models.CharField(max_length=64)),
                ('beneficiary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='beneficiary_income_expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('social_insurance_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('charity_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('social_warranty_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pension_agency_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('citizen_account_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('benefactor_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('housing_rent_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('electricity_bills_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('water_bills_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transportation_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('health_supplies_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('food_supplies_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('educational_supplies_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('proven_debts_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('beneficiary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('second_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('gender', models.CharField(max_length=5, null=True)),
                ('relationship', models.CharField(max_length=64)),
                ('educational_status', models.CharField(max_length=128, null=True)),
                ('marital_status', models.CharField(max_length=64)),
                ('national_id', models.CharField(max_length=20)),
                ('health_status', models.CharField(max_length=128, null=True)),
                ('needs_type', models.JSONField(default=list)),
                ('educational_degree', models.CharField(max_length=128, null=True)),
                ('date_of_birth', models.DateField()),
                ('national_id_exp_date', models.DateField(null=True)),
                ('needs_description', models.TextField(max_length=300)),
                ('educational_level', models.CharField(max_length=64, null=True)),
                ('disease_type', models.CharField(max_length=100, null=True)),
                ('beneficiary_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='Dependent_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dependent')),
            ],
        ),
        migrations.CreateModel(
            name='Individual_supporter_beneficiary_sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beneficiary')),
                ('individual_supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.individual_supporter')),
            ],
        ),
        migrations.CreateModel(
            name='Entity_supporter_operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=1, max_length=55)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=55)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.entity')),
                ('supporter_operation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supporter_operation')),
            ],
        ),
    ]
