# Generated by Django 4.2.5 on 2023-10-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_beneficiary_entity_individual_orphan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='national_id',
            field=models.CharField(max_length=20),
        ),
    ]
