# Generated by Django 5.0.1 on 2024-01-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
