# Generated by Django 4.2.5 on 2023-10-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_beneficiary_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='category',
        ),
    ]
