# Generated by Django 4.2.5 on 2023-10-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_entity_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='category',
        ),
    ]
