# Generated by Django 5.0.1 on 2024-01-22 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_beneficiary_last_updated_beneficiary_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary_request',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_beneficiary_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
