# Generated by Django 4.2.5 on 2023-10-05 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_individual_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporter_operation',
            name='entity_id',
        ),
        migrations.CreateModel(
            name='entity_supporter_operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default=1, max_length=55)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=55)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('entity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.entity')),
                ('supporter_operation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supporter_operation')),
            ],
        ),
    ]
