# Generated by Django 5.0.1 on 2024-01-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_beneficiary_request_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary_request',
            name='status',
            field=models.CharField(max_length=55),
        ),
    ]
