# Generated by Django 4.2.6 on 2023-10-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_supporter_operation_entity_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='name',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='first_name',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='last_name',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='middle_name',
            field=models.CharField(default='', max_length=55),
        ),
    ]
