# Generated by Django 4.2.6 on 2023-10-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_beneficiary_name_beneficiary_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'انثى')], max_length=1, null=True),
        ),
    ]
