# Generated by Django 5.0.1 on 2024-01-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_beneficiary_request_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='status',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
