# Generated by Django 4.2.6 on 2023-10-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_beneficiary_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='category',
            field=models.CharField(choices=[('Regular Family', 'أسرة عادية'), ('Orphan Family', 'أسرة أيتام'), ('Widowed Family', 'أسرة أرملة'), ('Prisoners Family', 'أسرة سجناء'), ('Divorced Family', 'أسرة مطلقة'), ('Individual', 'فرد')], max_length=55),
        ),
    ]
