# Generated by Django 4.2.6 on 2023-10-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_beneficiary_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='category',
            field=models.CharField(choices=[('regular family', 'أسرة عادية'), ('orphan family', 'أسرة أيتام'), ('widowed family', 'أسرة أرملة'), ('prisoners family', 'أسرة سجناء'), ('divorced family', 'أسرة مطلقة'), ('individual', 'فرد')], max_length=55),
        ),
    ]
