# Generated by Django 5.0.1 on 2024-01-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_beneficiary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='national_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
