# Generated by Django 4.2.6 on 2023-10-26 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_beneficiary_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='date_of_death_of_father_or_husband',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='disease_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='educational_status',
            field=models.CharField(choices=[('none', 'لا يوجد'), ('primary', 'ابتدائي'), ('middle', 'متوسط'), ('secondary', 'ثانوي'), ('university', 'جامعي')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='employer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='health_status',
            field=models.CharField(choices=[('good', 'جيدة'), ('not good', 'غير جيدة')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='national_id_exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='signup_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='washing_place',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='work_status',
            field=models.CharField(choices=[('yes', 'نعم'), ('no', 'لا')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(code='nomatch', message='Enter a valid phone number', regex='^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,6}$')]),
        ),
    ]
