# Generated by Django 5.0.1 on 2024-01-28 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_dependent_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity_supporter_operation',
            name='entity_id',
        ),
        migrations.RemoveField(
            model_name='entity_supporter_operation',
            name='supporter_operation_id',
        ),
        migrations.DeleteModel(
            name='individual',
        ),
        migrations.DeleteModel(
            name='entity',
        ),
        migrations.DeleteModel(
            name='Entity_supporter_operation',
        ),
        migrations.DeleteModel(
            name='supporter_operation',
        ),
    ]
