# Generated by Django 4.2.6 on 2023-10-26 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_beneficiary_date_of_death_of_father_or_husband_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='educational_status',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='educational_level',
            field=models.CharField(choices=[('primary-1', 'أول ابتدائي'), ('primary-2', 'ثاني ابتدائي'), ('primary-3', 'ثالث ابتدائي'), ('primary-4', 'رابع ابتدائي'), ('primary-5', 'خامس ابتدائي'), ('primary-6', 'سادس ابتدائي'), ('middle-1', 'اول متوسط'), ('middle-2', 'ثاني متوسط'), ('middle-3', 'ثالث متوسط'), ('secondary-1', 'اول ثانوي'), ('secondary-2', 'ثاني ثانوي'), ('secondary-3', 'ثالث ثانوي'), ('university', 'جامعي'), ('none', 'لا يدرس')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('status', models.CharField(default=1, max_length=55)),
                ('justifications', models.CharField(max_length=500)),
                ('needs', models.TextField(max_length=500)),
                ('family_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beneficiary')),
            ],
        ),
        migrations.CreateModel(
            name='dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('middle_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'انثى')], max_length=1, null=True)),
                ('relationship', models.CharField(choices=[('son', 'ابن'), ('daughter', 'ابنة'), ('husband/wife', 'زوج/ـة'), ('maternal aunt/maternal uncle', 'خال/ـة'), ('paternal aunt/paternal uncle', 'عم/ـة'), ('grandmother/grandfather', 'جد/ـة')], max_length=55)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=20)),
                ('national_id_exp_date', models.DateField(null=True)),
                ('marital_status', models.CharField(choices=[('married', 'متزوج/ـة'), ('single', 'أعزب/ـة'), ('widower', 'أرمل/ـة'), ('divorced', 'مطلقة')], max_length=55)),
                ('educational_level', models.CharField(choices=[('primary-1', 'أول ابتدائي'), ('primary-2', 'ثاني ابتدائي'), ('primary-3', 'ثالث ابتدائي'), ('primary-4', 'رابع ابتدائي'), ('primary-5', 'خامس ابتدائي'), ('primary-6', 'سادس ابتدائي'), ('middle-1', 'اول متوسط'), ('middle-2', 'ثاني متوسط'), ('middle-3', 'ثالث متوسط'), ('secondary-1', 'اول ثانوي'), ('secondary-2', 'ثاني ثانوي'), ('secondary-3', 'ثالث ثانوي'), ('university', 'جامعي'), ('none', 'لا يدرس')], max_length=55, null=True)),
                ('educational_status', models.CharField(choices=[('none', 'لا يوجد'), ('primary', 'ابتدائي'), ('middle', 'متوسط'), ('secondary', 'ثانوي'), ('university', 'جامعي')], max_length=55, null=True)),
                ('health_status', models.CharField(choices=[('good', 'جيدة'), ('not good', 'غير جيدة')], max_length=100, null=True)),
                ('disease_type', models.CharField(max_length=100, null=True)),
                ('total_income', models.IntegerField()),
                ('income_source', models.CharField(choices=[('salary', 'الراتب'), ('social development', 'التأمينات الاجتماعية'), ('social security system', 'الضمان الاجتماعي'), ('retired services', 'مصلحة التقاعد'), ('citizen account', 'حساب المواطن'), ('social security office', 'التأهيل الشامل'), ('charity', 'جمعية خيرية'), ('benefactor', 'فاعل خير'), ('other', 'اخرى')], max_length=100)),
                ('needs_type', models.CharField(choices=[('economic', 'اقتصادي'), ('healthy', 'صحي'), ('educational', 'تعليمي'), ('employment', 'توظيف'), ('sponsorship', 'كفالة')], max_length=100)),
                ('needs_description', models.TextField(max_length=300)),
                ('family_head_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.family')),
            ],
        ),
    ]
