# Generated by Django 4.2.6 on 2023-12-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_beneficiary_educational_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='date_of_death_of_father_or_husband',
            new_name='death_date_father_husband',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
