# Generated by Django 5.0.1 on 2024-01-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_entity_supporter_operation_entity_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter_beneficiary_sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount_donated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beneficiary')),
                ('individual_supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.individual_supporter')),
            ],
        ),
        migrations.DeleteModel(
            name='Individual_supporter_beneficiary_sponsorship',
        ),
    ]
