# Generated by Django 4.2.6 on 2023-12-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_date_of_death_of_father_or_husband_beneficiary_death_date_father_husband_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='marital_status',
            field=models.CharField(choices=[('married', 'متزوج/ـة'), ('single', 'أعزب/ـة'), ('widower', 'أرمل/ـة'), ('divorced', 'مطلقة'), ('deserted', 'مهجورة')], max_length=55),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='marital_status',
            field=models.CharField(choices=[('married', 'متزوج/ـة'), ('single', 'أعزب/ـة'), ('widower', 'أرمل/ـة'), ('divorced', 'مطلقة'), ('deserted', 'مهجورة')], max_length=55),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='relationship',
            field=models.CharField(choices=[('son', 'ابن'), ('daughter', 'ابنة'), ('brother', 'أخ'), ('sister', 'أخت'), ('husband/wife', 'زوج/ـة'), ('maternal aunt/maternal uncle', 'خال/ـة'), ('paternal aunt/paternal uncle', 'عم/ـة'), ('grandmother/grandfather', 'جد/ـة')], max_length=55),
        ),
    ]
