# Generated by Django 4.2.6 on 2023-12-03 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_beneficiary_marital_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='beneficiary_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.CharField(max_length=64)),
                ('street_name', models.CharField(max_length=64)),
                ('neighborhood', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=64)),
                ('additional_number', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=64)),
                ('location_url', models.CharField(max_length=1064)),
                ('housing_type', models.CharField(max_length=64)),
                ('housing_ownership', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='beneficiary_income_expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('social_insurance_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('charity_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('social_warranty_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pension_agency_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('citizen_account_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('benefactor_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_in', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('housing_rent_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('electricity_bills_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('water_bills_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transportation_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('health_supplies_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('food_supplies_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('educational_supplies_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('proven_debts_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_ex', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='orphan',
            name='beneficiary_id',
        ),
        migrations.RemoveField(
            model_name='orphan_supporter_operation',
            name='orphan_id',
        ),
        migrations.RemoveField(
            model_name='orphan_supporter_operation',
            name='supporter_operation_id',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='signup_at',
            new_name='receivedAt',
        ),
        migrations.RenameField(
            model_name='dependent',
            old_name='middle_name',
            new_name='second_name',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='inquiries',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='justifications',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='national_address',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='dependent',
            name='family_head_id',
        ),
        migrations.RemoveField(
            model_name='dependent',
            name='total_income',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_iban',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='family_issues',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='family_needs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='reviewedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='second_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dependent',
            name='beneficiary_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.beneficiary'),
        ),
        migrations.AddField(
            model_name='dependent',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='category',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='disease_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='educational_level',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='employer',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='file_no',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='first_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='gender',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='health_status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='last_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='marital_status',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='nationality',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='washing_place',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='work_status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='educational_level',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='educational_status',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='gender',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='health_status',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='income_source',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='marital_status',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='needs_type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='relationship',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='family',
        ),
        migrations.DeleteModel(
            name='orphan',
        ),
        migrations.DeleteModel(
            name='orphan_supporter_operation',
        ),
        migrations.AddField(
            model_name='beneficiary_income_expense',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beneficiary'),
        ),
        migrations.AddField(
            model_name='beneficiary_house',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beneficiary'),
        ),
    ]
