# Generated by Django 4.2.6 on 2023-12-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_beneficiary_house_beneficiary_income_expense_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary_house',
            old_name='beneficiary',
            new_name='beneficiary_id',
        ),
        migrations.RenameField(
            model_name='beneficiary_income_expense',
            old_name='beneficiary',
            new_name='beneficiary_id',
        ),
    ]
