# Generated by Django 5.0.1 on 2024-02-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_supporter_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supporter_beneficiary_sponsorship',
            old_name='amount_donated',
            new_name='amount_donated_monthly',
        ),
        migrations.RenameField(
            model_name='supporter_beneficiary_sponsorship',
            old_name='individual_supporter',
            new_name='supporter',
        ),
        migrations.RemoveField(
            model_name='supporter',
            name='orphan_number',
        ),
        migrations.AddField(
            model_name='supporter',
            name='invite_beneficiary',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='supporter',
            name='status_notify',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='supporter',
            name='visit_beneficiary',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='supporter',
            name='was_sponsor',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='supporter_beneficiary_sponsorship',
            name='total_amount_donated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='supporter_request',
            name='beneficiary_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='supporter_request',
            name='donation_type',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='supporter_request',
            name='duration',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='supporter_request',
            name='orphan_donation_type',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='supporter_request',
            name='orphan_number',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='supporter_request',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='supporter_request',
            name='widower_donation_type',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='supporter_request',
            name='widower_number',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
