# Generated by Django 4.2.6 on 2023-12-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_beneficiary_beneficiary_house_beneficiary_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='is_qualified',
            field=models.IntegerField(default=0),
        ),
    ]
