# Generated by Django 4.2.6 on 2023-12-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_beneficiary_is_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependent',
            name='educational_degree',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='needs_type',
            field=models.JSONField(default=list),
        ),
    ]
