# Generated by Django 5.0.1 on 2024-02-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_supporter_request_orphan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter_request',
            name='selection_type',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
