# Generated by Django 5.0.1 on 2024-02-05 20:13

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_supporter_request_selection_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter_request_attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=256, null=True)),
                ('file_object', models.FileField(blank=True, null=True, upload_to=myapp.models.supporter_request_file_directory)),
                ('supporter_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.supporter_request')),
            ],
        ),
    ]
