# Generated by Django 4.2.6 on 2023-12-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_dependent_educational_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary_income_expense',
            name='in_ex_diff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='beneficiary_income_expense',
            name='total_ex',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='beneficiary_income_expense',
            name='total_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='reviewedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
