# Generated by Django 5.0.1 on 2024-02-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_supporter_request_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary_request',
            name='reviewed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='supporter_request',
            name='reviewed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
