# Generated by Django 4.2.6 on 2023-12-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_beneficiary_income_expense_in_ex_diff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary_income_expense',
            name='in_ex_diff',
        ),
        migrations.RemoveField(
            model_name='beneficiary_income_expense',
            name='total_ex',
        ),
        migrations.RemoveField(
            model_name='beneficiary_income_expense',
            name='total_in',
        ),
    ]
