# Generated by Django 4.2.6 on 2023-12-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_beneficiary_income_expense_in_ex_diff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='file_beneficiary_national_id',
            field=models.FileField(null=True, upload_to='beneficiary_national_id/'),
        ),
    ]
