# Generated by Django 4.2.6 on 2024-01-02 20:48

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_beneficiary_file_beneficiary_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='file_beneficiary_national_address',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_national_address_directory_path),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='file_children_responsibility_deed',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_children_responsibility_deed_directory_path),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='file_debt_instrument',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_debt_instrument_directory_path),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='file_divorce_deed',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_divorce_deed_directory_path),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='file_father_husband_death_certificate',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_father_husband_death_certificate_directory_path),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='file_lease_contract_title_deed',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_lease_contract_title_deed_directory_path),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='file_letter_from_prison',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_letter_from_prison_directory_path),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='file_national_id_dependents',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_national_id_dependents_directory_path),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='file_other_files',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_other_files_directory_path),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='file_pension_social_insurance_inquiry',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_pension_social_insurance_inquiry_directory_path),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='file_social_warranty_inquiry',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_social_warranty_inquiry_directory_path),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='file_water_electricity_bills',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_water_electricity_bills_directory_path),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='file_beneficiary_national_id',
            field=models.FileField(null=True, upload_to=myapp.models.beneficiary_national_id_directory_path),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
