# Generated by Django 4.2.6 on 2024-01-03 23:46

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_beneficiary_file_beneficiary_national_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_beneficiary_national_address',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_beneficiary_national_id',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_children_responsibility_deed',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_debt_instrument',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_divorce_deed',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_father_husband_death_certificate',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_lease_contract_title_deed',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_letter_from_prison',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_national_id_dependents',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_other_files',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_pension_social_insurance_inquiry',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_social_warranty_inquiry',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='file_water_electricity_bills',
        ),
        migrations.CreateModel(
            name='Beneficiary_attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_beneficiary_national_id', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_national_id_directory_path)),
                ('file_beneficiary_national_address', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_national_address_directory_path)),
                ('file_debt_instrument', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_debt_instrument_directory_path)),
                ('file_pension_social_insurance_inquiry', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_pension_social_insurance_inquiry_directory_path)),
                ('file_father_husband_death_certificate', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_father_husband_death_certificate_directory_path)),
                ('file_letter_from_prison', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_letter_from_prison_directory_path)),
                ('file_divorce_deed', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_divorce_deed_directory_path)),
                ('file_children_responsibility_deed', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_children_responsibility_deed_directory_path)),
                ('file_other_files', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_other_files_directory_path)),
                ('file_lease_contract_title_deed', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_lease_contract_title_deed_directory_path)),
                ('file_water_electricity_bills', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_water_electricity_bills_directory_path)),
                ('file_national_id_dependents', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_national_id_dependents_directory_path)),
                ('file_social_warranty_inquiry', models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_social_warranty_inquiry_directory_path)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beneficiary')),
            ],
        ),
    ]
