# Generated by Django 4.2.6 on 2024-01-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_beneficiary_file_beneficiary_national_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary_attachment',
            old_name='file_beneficiary_national_id',
            new_name='file_object',
        ),
        migrations.RemoveField(
            model_name='beneficiary_attachment',
            name='file_beneficiary_national_address',
        ),
        migrations.RemoveField(
            model_name='beneficiary_attachment',
            name='file_children_responsibility_deed',
        ),
        migrations.RemoveField(
            model_name='beneficiary_attachment',
            name='file_debt_instrument',
        ),
        migrations.RemoveField(
            model_name='beneficiary_attachment',
            name='file_divorce_deed',
        ),
        migrations.RemoveField(
            model_name='beneficiary_attachment',
            name='file_father_husband_death_certificate',
        ),
        migrations.RemoveField(
            model_name='beneficiary_attachment',
            name='file_lease_contract_title_deed',
        ),
        migrations.RemoveField(
            model_name='beneficiary_attachment',
            name='file_letter_from_prison',
        ),
        migrations.RemoveField(
            model_name='beneficiary_attachment',
            name='file_national_id_dependents',
        ),
        migrations.RemoveField(
            model_name='beneficiary_attachment',
            name='file_other_files',
        ),
        migrations.RemoveField(
            model_name='beneficiary_attachment',
            name='file_pension_social_insurance_inquiry',
        ),
        migrations.RemoveField(
            model_name='beneficiary_attachment',
            name='file_social_warranty_inquiry',
        ),
        migrations.RemoveField(
            model_name='beneficiary_attachment',
            name='file_water_electricity_bills',
        ),
    ]
