# Generated by Django 5.0.1 on 2024-03-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_support_operation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_operation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
