# Generated by Django 4.2.6 on 2024-01-04 00:19

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_file_beneficiary_national_id_beneficiary_attachment_file_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary_attachment',
            name='file_object',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.beneficiary_file_directory),
        ),
    ]
