# Generated by Django 5.0.1 on 2024-03-02 21:04

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_support_operation_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_operation_attachment',
            name='file_object',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.support_operation_file_directory),
        ),
        migrations.CreateModel(
            name='Field_visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_after_visit', models.CharField(max_length=1024)),
                ('visit_type', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.beneficiary')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field_visit_attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=256, null=True)),
                ('file_object', models.FileField(blank=True, null=True, upload_to=myapp.models.field_visit_file_directory)),
                ('field_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.field_visit')),
            ],
        ),
    ]
