# Generated by Django 4.2.6 on 2024-01-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_beneficiary_attachment_file_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary_attachment',
            name='file_type',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
