# Generated by Django 5.0.1 on 2024-08-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_support_operation_attachment_file_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_password_passed', models.BooleanField(default=False)),
            ],
        ),
    ]
