# Generated by Django 4.2.6 on 2024-01-18 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_beneficiary_attachment_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='income_amount',
        ),
        migrations.RemoveField(
            model_name='dependent',
            name='income_source',
        ),
        migrations.CreateModel(
            name='Dependent_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dependent')),
            ],
        ),
    ]
