# Generated by Django 5.0.7 on 2024-09-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_customuser_national_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordCheck',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='national_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='national_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
