# Generated by Django 5.0.7 on 2024-10-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_beneficiary_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_id_exp_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='national_id',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='nationality',
            field=models.CharField(default='none', max_length=64),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(default=0, max_length=15, unique=True),
        ),
    ]
