# Generated by Django 5.0.7 on 2024-10-24 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_customuser_national_id_exp_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='email',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='national_id_exp_date',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='phone_number',
        ),
    ]
