# Generated by Django 5.0.7 on 2024-12-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_authentication_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='second_name',
        ),
    ]
