# Generated by Django 5.0.7 on 2024-12-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_dependent_bank_iban_dependent_bank_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary_attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary_attachment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
