# Generated by Django 5.0.7 on 2024-12-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_beneficiary_attachment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication_otp',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
