# Generated by Django 5.0.7 on 2025-01-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_alter_authentication_otp_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_phone_number_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number_verified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
