# Generated by Django 5.0.7 on 2025-01-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_customuser_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication_otp',
            name='user_agent',
            field=models.CharField(max_length=512),
        ),
    ]
